/* ---- ivm ispstub: fake ISP firmware, boot handshake (inserted by exp/ispstub.py) ----
 * H10 ISP (version 10), GPIO mailbox block at region0 +0x1ae4100 (GPIO0..GPIO7 = +0x00..+0x1c).
 * AppleH10CamIn::ISP_StartFirmware, preloaded-firmware path (DT isp pre-loaded + segment-ranges):
 *   kext: zero GPIO0..7, write 0x10 to +0x1400044 (release the ISP CPU)
 *   fw:   GPIO0 = number of IPC channels, GPIO1 = IPC queue size - 1, GPIO3 = extra heap size,
 *         GPIO4 = 0 (no unit-test mode), GPIO7 = 0x8042006 (wake)
 *   kext: GPIO0 = boot-args ISP address, GPIO7 = 0xf7fbdff9, reads GPIO7 back expecting 0x8042006
 *   fw:   GPIO0 = ISP address of the channel table (n x 0x100: name[64], type, src, num, iova at 0x4c)
 *   kext: GPIO3 = 0x8042006, polls until GPIO3 == 0
 * ISP addresses are offsets into the consolidated firmware mapping (our carve-out), see ispAddressToHostAddress.
 */
/* v10 (0x1ae4100) or v9 (0x1aa4100) block, chosen by the kext from the ISP version; serve both */
static const uint32_t ivm_isp_gbase[2] = { 0x1ae4100u, 0x1aa4100u };
#define IVM_ISP_GPIO(n)     (gb + 4u * (n))
#define IVM_ISP_CPU_RUN     0x1400044u
#define IVM_ISP_TABLE       0x100000u
#define IVM_ISP_RING0       0x110000u
#define IVM_ISP_RING_STRIDE 0x10000u

typedef struct {
    const char* name;
    uint32_t    type, src, num;
} IvmIspChan;

/* Asahi apple-isp naming: type 0 = command (host to fw), 1 = reply, 2 = report (fw to host) */
static const IvmIspChan ivm_isp_chans[] = {
    { "TERMINAL", 2, 0, 16 },
    { "IO", 0, 1, 8 },
    { "DEBUG", 0, 2, 8 },
    { "BUF_H2T", 0, 3, 64 },
    { "BUF_T2H", 1, 3, 64 },
    { "SHAREDMALLOC", 1, 3, 8 },
    { "IO_T2H", 1, 3, 8 },
};

static qemu_irq ivm_isp_irq;      /* AIC line of isp interrupts[0] (kext registers index 0) */
static uint32_t ivm_isp_pend;     /* pending sources: bit (1 << channel src) */
static long     ivm_isp_ncmd;
static AddressSpace ivm_isp_dma_as;   /* ISP view through dart-isp (mapper-isp SID) */
static bool     ivm_isp_dma_ok;

static void ivm_isp_set(uint32_t off, uint32_t val)
{
    g_hash_table_insert(ivm_isp_regs, GUINT_TO_POINTER(off), GUINT_TO_POINTER(val));
}

/* ---- command responses (Asahi isp-cmd.h layouts: u64 opcode word, then payload) ---- */
static void ivm_isp_put32(uint8_t* b, uint32_t len, uint32_t off, uint32_t v)
{
    if (off + 4 <= len) {
        stl_le_p(b + off, v);
    }
}

static void ivm_isp_put16(uint8_t* b, uint32_t len, uint32_t off, uint16_t v)
{
    if (off + 2 <= len) {
        stw_le_p(b + off, v);
    }
}

static void ivm_isp_putstr(uint8_t* b, uint32_t len, uint32_t off, const char* str, uint32_t max)
{
    uint32_t n = strlen(str);
    if (n > max - 1) {
        n = max - 1;
    }
    if (off + n < len) {
        memcpy(b + off, str, n);
    }
}

/* channel -> sensor (platform table, iPhone 11 / sensor-type 0xaf: 0 rear, 2 frnt, 3 firc (Face ID IR), 4 resw) */
static uint16_t ivm_isp_sensor_id(uint32_t ch)
{
    /* IVM_ISP_CHMASK: channels to report (default 0x5 = rear wide + front). The super-wide (ch4, 0x10)
     * makes CMCapture build the "Back Dual Wide" device whose BWPreviewStitcherNode needs real module
     * calibration (init fails -> session commit -12780), so it is off by default. */
    static int mask = -1;
    if (mask < 0) {
        const char* e = getenv("IVM_ISP_CHMASK");
        mask = e ? (int)strtol(e, NULL, 0) : 0x5;
    }
    if (ch >= 31 || !(mask & (1 << ch))) {
        return 0;
    }
    switch (ch) {
    case 0: return 0x0503;   /* back wide */
    case 2: return 0x0514;   /* front (CameraSetup.plist DefaultSensorIDs) */
    case 4: return 0x0372;   /* back super wide */
    default: return 0;       /* 1, 5 absent; 3 (IR) not modelled */
    }
}


/* per-sensor camera configs (index = H10ISP output-preset config index; dims from the preset tables,
 * fps/binned/SIFR matched to N104 FigCaptureStreamFormats). Generated by ivm/lab/cam/tools/gencfg.py. */
typedef struct {
    uint16_t sensor, idx, w, h, fps, binned, sifr;
} IvmIspCamCfg;
static const IvmIspCamCfg ivm_isp_camcfgs[] = {
    { 0x503,  0, 4224, 3176, 120, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x503,  1, 4224, 3168,  60, 0, 1 }, /* Photo */
    { 0x503,  2, 4224, 3176, 120, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x503,  3, 4224, 3176, 120, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x503,  4, 4224, 3176, 120, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x503,  5, 4224, 3168,  30, 0, 1 }, /* Video-FullSensor-30 */
    { 0x503,  6, 4224, 3176, 120, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x503,  7, 2112, 1188, 240, 1, 0 }, /* Video-Binned-FES-240 */
    { 0x503,  8, 2112, 1188, 240, 1, 0 }, /* Video-Binned-240 */
    { 0x503,  9, 4224, 3176, 120, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x503, 11, 2112, 1188, 240, 1, 0 }, /* Video-Binned-FES-240 */
    { 0x503, 13, 4224, 3024,  30, 0, 1 }, /* Photo_NoVerticalOverScan */
    { 0x503, 14, 4224, 2376, 120, 0, 0 }, /* Video-120 */
    { 0x503, 15, 4224, 2384,  60, 0, 1 }, /* Video-FES-60 */
    { 0x503, 16, 2112, 1512,  60, 1, 0 }, /* Video-Binned-60 */
    { 0x503, 20, 4032, 3024,  30, 0, 0 }, /* - */
    { 0x372,  0, 4224, 3024,  30, 0, 1 }, /* Photo */
    { 0x372,  1, 4032, 3024,  30, 0, 0 }, /* - */
    { 0x372,  2, 4224, 2376,  30, 0, 0 }, /* - */
    { 0x372,  3, 2112, 1188,  30, 1, 0 }, /* - */
    { 0x372,  4, 2112, 1188,  30, 1, 0 }, /* - */
    { 0x372,  5, 2112, 1188,  30, 1, 0 }, /* - */
    { 0x372,  6, 4224, 3024,  30, 0, 1 }, /* Photo_NoVerticalOverScan */
    { 0x372,  7, 4224, 2384,  30, 0, 0 }, /* - */
    { 0x372,  8, 2112, 1512,  60, 1, 0 }, /* Video-Binned-FES-60 */
    { 0x514,  0, 4032, 3024,  30, 0, 1 }, /* Photo-3088x2316 */
    { 0x514,  1, 3136, 2352,  30, 0, 0 }, /* - */
    { 0x514,  2, 4032, 2272,  60, 0, 0 }, /* Video-FES-60 */
    { 0x514,  3, 2016, 1136, 120, 1, 0 }, /* Video-Binned-120 */
    { 0x514,  4, 4032, 3024,  60, 0, 0 }, /* Video-4by3-Low-Resolution */
    { 0x514,  5, 3136, 2352,  30, 0, 0 }, /* - */
    { 0x514,  6, 4032, 2272,  60, 0, 0 }, /* Video-60 */
    { 0x514,  7, 2016, 1512,  60, 1, 0 }, /* Video-4by3-Binned-FES-60 */
};

static const IvmIspCamCfg* ivm_isp_camcfg(uint16_t sensor, uint32_t idx)
{
    static const IvmIspCamCfg dflt = { 0, 0, 4032, 3024, 30, 0, 0 };
    const IvmIspCamCfg*       best = NULL;
    size_t                    i;
    for (i = 0; i < sizeof(ivm_isp_camcfgs) / sizeof(ivm_isp_camcfgs[0]); i++) {
        if (ivm_isp_camcfgs[i].sensor == sensor) {
            if (ivm_isp_camcfgs[i].idx == idx) {
                return &ivm_isp_camcfgs[i];
            }
            if (!best) {
                best = &ivm_isp_camcfgs[i];
            }
        }
    }
    return best ? best : &dflt;
}

static uint32_t ivm_isp_ncfg(uint16_t sensor)
{
    uint32_t n = 0;
    size_t   i;
    for (i = 0; i < sizeof(ivm_isp_camcfgs) / sizeof(ivm_isp_camcfgs[0]); i++) {
        if (ivm_isp_camcfgs[i].sensor == sensor && ivm_isp_camcfgs[i].idx + 1u > n) {
            n = ivm_isp_camcfgs[i].idx + 1u;
        }
    }
    return n ? n : 1;
}

static bool ivm_isp_cmd_respond(uint8_t* b, uint32_t len, uint16_t op)
{
    uint32_t ch = len >= 12 ? ldl_le_p(b + 8) : 0;
    switch (op) {
    case 0x0003:   /* CONFIG_GET */
        ivm_isp_put32(b, len, 0x08, 24000000);   /* timestamp_freq */
        ivm_isp_put32(b, len, 0x0c, 6);          /* num_channels (driver max 6) */
        return true;
    case 0x0006:   /* BUILDINFO */
        ivm_isp_putstr(b, len, 0x28, "Oct  4 2026", 0x20);
        ivm_isp_putstr(b, len, 0x48, "ivm-hle-isp 1.0", 0x60);
        return true;
    case 0x010d:   /* CH_INFO_GET */
        if (!ivm_isp_sensor_id(ch)) {
            return false;
        }
        ivm_isp_put32(b, len, 0x0c, 0x7da0001);
        ivm_isp_put32(b, len, 0x10, 0x300ac);
        ivm_isp_put32(b, len, 0x14, 0x40007);
        ivm_isp_put32(b, len, 0x18, 0x5);
        ivm_isp_put32(b, len, 0x1c, 0x1);
        ivm_isp_put32(b, len, 0x20, ivm_isp_sensor_id(ch));
        ivm_isp_put32(b, len, 0x24, 0x7);
        ivm_isp_put32(b, len, 0x28, 0x1);
        ivm_isp_put32(b, len, 0x2c, 0x7);
        ivm_isp_put32(b, len, 0x4c, 0x10000);
        ivm_isp_put32(b, len, 0x50, 0x1);
        ivm_isp_put32(b, len, 0x58, 0x4);
        ivm_isp_put32(b, len, 0x5c, 0x10);
        {   /* num camera configs ("presets"): H10ISP output-preset tables index configs up to 0x14 (IMX503) */
            const char* e = getenv("IVM_ISP_NCFG");
            ivm_isp_put32(b, len, 0x60, e ? (uint32_t)atoi(e) : ivm_isp_ncfg(ivm_isp_sensor_id(ch)));
        }
        ivm_isp_put32(b, len, 0x68, 0x44c0);
        ivm_isp_put32(b, len, 0x6c, 0x40);
        ivm_isp_put32(b, len, 0x70, 0x1);
        ivm_isp_put32(b, len, 0x74, 0x2);
        ivm_isp_put32(b, len, 0x78, 0x4000);
        ivm_isp_put32(b, len, 0x7c, 0x40);
        ivm_isp_put32(b, len, 0x80, 0x1);
        ivm_isp_put32(b, len, 0x84, 0x4d564900u | ch);   /* sensor SN (8 bytes) */
        ivm_isp_put32(b, len, 0x88, 0x2026);
        ivm_isp_put32(b, len, 0x8c, 0x36);
        ivm_isp_put32(b, len, 0x98, 24000000);
        {
            char sn[20];
            snprintf(sn, sizeof(sn), "IVMCAM%02u0001", ch);
            ivm_isp_putstr(b, len, 0x9e, sn, 18);
        }
        ivm_isp_put32(b, len, 0xb4, 0x8);
        ivm_isp_put32(b, len, 0xc0, 0x4);
        ivm_isp_put32(b, len, 0xdc, 0xff0000);
        ivm_isp_put32(b, len, 0xe0, 0xc00);
        ivm_isp_put32(b, len, 0xe8, 0x1c);
        ivm_isp_put32(b, len, 0xec, 0x640);
        ivm_isp_put32(b, len, 0xf0, 0x4);
        ivm_isp_put32(b, len, 0xf4, 0x4);
        return true;
    case 0x0105:   /* CH_CAMERA_CONFIG_CURRENT_GET */
    case 0x0106: { /* CH_CAMERA_CONFIG_GET */
        /* H10 sCIspCameraConfig = resp[0x10..0xac] (offsets below are resp offsets = cfg + 0x10), from
         * H10ISP CacheDeviceConfigs / CopySupportedFormatsArray: +0x10/+0x12 w/h, +0x14/+0x16 output w/h,
         * +0x18/+0x1a binning H/V (0 none, 1 = 2x), +0x1c max fps u16 8.8, +0x1e min fps 8.8,
         * +0x70 max / +0x74 min integration time, +0x94/+0x98 SensorWidth/Height (u32),
         * +0x9c SIFR enabled u16, +0x9e SIFR binning. Values per (sensor, config index) chosen so the
         * resulting stream formats resolve against N104 AVCaptureSession.plist FigCaptureStreamFormats. */
        uint32_t                 cfg = len >= 0x10 ? ldl_le_p(b + 0xc) : 0;
        const IvmIspCamCfg*      c   = ivm_isp_camcfg(ivm_isp_sensor_id(ch), cfg);
        ivm_isp_put16(b, len, 0x10, c->w);
        ivm_isp_put16(b, len, 0x12, c->h);
        ivm_isp_put16(b, len, 0x14, c->w);
        ivm_isp_put16(b, len, 0x16, c->h);
        ivm_isp_put16(b, len, 0x18, c->binned);
        ivm_isp_put16(b, len, 0x1a, c->binned);
        ivm_isp_put16(b, len, 0x1c, c->fps << 8);
        /* firmware buffer-pool ids per output (H10ISP Activate*OutputInFrameReceiver pass them to
         * addBufferPoolToFrameReceiver; 0/2 are the metadata pools, duplicates fail with 0xe00002e2):
         * cfg+0x10 primary scaler, +0x50 intermediate tap, +0x54 still image, +0x5c secondary scaler. */
        ivm_isp_put32(b, len, 0x20, 3);
        ivm_isp_put32(b, len, 0x60, 4);
        ivm_isp_put32(b, len, 0x64, 5);
        ivm_isp_put32(b, len, 0x6c, 6);
        ivm_isp_put16(b, len, 0x1e, 2 << 8);
        ivm_isp_put32(b, len, 0x70, 500000);
        ivm_isp_put32(b, len, 0x74, 10);
        ivm_isp_put32(b, len, 0x94, c->w);
        ivm_isp_put32(b, len, 0x98, c->h);
        ivm_isp_put16(b, len, 0x9c, c->sifr);
        ivm_isp_put16(b, len, 0x9e, c->sifr ? 1 : 0);
        return true;
    }
    case 0x0116: { /* CH_BUFFER_POOL_CONFIG_GET: H10ISPDevice::GetPoolInfo reads count @0xc and 0x10-byte
                    * entries @0x10 {u16 dynamic pool type, u16 pool id, u32 ?, u32 pool size}. One distinct pool
                    * per type (all-zero answer made every pool id 0 -> addBufferPoolToFrameReceiver 0xe00002e2). */
        uint32_t t, max = len >= 0x10 ? ldl_le_p(b + 0xc) : 0;
        if (max > 0x1d) {
            max = 0x1d;
        }
        for (t = 0; t < max && 0x10 + (t + 1) * 0x10 <= len; t++) {
            ivm_isp_put16(b, len, 0x10 + t * 0x10, t);
            ivm_isp_put16(b, len, 0x12 + t * 0x10, t + 3);   /* ids 0/2 are taken by the metadata pools */
            ivm_isp_put32(b, len, 0x18 + t * 0x10, 8);
        }
        ivm_isp_put32(b, len, 0xc, t);
        return true;
    }
    default:
        return false;
    }
}

static void ivm_isp_ring_rw(uint32_t ring, uint32_t slot, uint32_t* w0, bool wr)
{
    hwaddr a = ivm_isp_fw_phys + ring + slot * 0x40u;
    if (wr) {
        uint32_t le = cpu_to_le32(*w0);
        address_space_write(&address_space_memory, a, MEMTXATTRS_UNSPECIFIED, &le, 4);
    } else {
        uint32_t le = 0;
        address_space_read(&address_space_memory, a, MEMTXATTRS_UNSPECIFIED, &le, 4);
        *w0 = le32_to_cpu(le);
    }
}

@@IVM_FRAMES@@
/* IOProcessorChannel slots are 64 B: w0 = ISP address | turn bit0, w1, w2.  Command (type 0) rings: host
 * writes bit0 = 0, fw completes by setting bit0 = 1 (cmd+6 ack stays 0 = success).  Other rings start owned by
 * fw (bit0 = 1).  Completion raises pending bit (1 << src) at +0x1ae0100, host W1C-clears via +0x1ae4a0c. */
static void ivm_isp_doorbell(uint32_t gb, uint32_t bits)
{
    uint32_t i, k, w0, w[3], done = 0;
    ivm_isp_sm_poll();
    for (i = 0; i < ARRAY_SIZE(ivm_isp_chans); i++) {
        uint32_t ring = IVM_ISP_RING0 + i * IVM_ISP_RING_STRIDE;
        if (ivm_isp_chans[i].type != 0 || !((bits >> ivm_isp_chans[i].src) & 1)) {
            continue;
        }
        for (k = 0; k < ivm_isp_chans[i].num; k++) {
            ivm_isp_ring_rw(ring, k, &w0, false);
            if (w0 & 1) {
                continue;
            }
            address_space_read(&address_space_memory, ivm_isp_fw_phys + ring + k * 0x40u, MEMTXATTRS_UNSPECIFIED, w, 12);
            if (ivm_isp_ncmd++ < 2000) {
                uint8_t c[24] = { 0 };
                char hex[64];
                uint32_t n;
                if (ivm_isp_dma_ok) {
                    address_space_read(&ivm_isp_dma_as, le32_to_cpu(w[0]) & ~3u, MEMTXATTRS_UNSPECIFIED, c, sizeof(c));
                }
                for (n = 0; n < sizeof(c); n++) {
                    snprintf(hex + 2 * n, 3, "%02x", c[n]);
                }
                fprintf(stderr, "[ivm-isp] fw: cmd #%ld %s[%u] addr=0x%x len=0x%x op=0x%04x [%s] -> ack\n", ivm_isp_ncmd,
                        ivm_isp_chans[i].name, k, le32_to_cpu(w[0]), le32_to_cpu(w[1]), lduw_le_p(c + 4), hex);
            }
            if (ivm_isp_dma_ok && i == IVM_ISP_CH_H2T) {
                ivm_isp_h2t(le32_to_cpu(w[0]) & ~3u);
            } else if (ivm_isp_dma_ok) {
                uint32_t len = le32_to_cpu(w[1]);
                uint32_t a = le32_to_cpu(w[0]) & ~3u;
                if (len >= 8 && len <= 0x1000) {
                    uint8_t* pk = g_malloc0(len);
                    address_space_read(&ivm_isp_dma_as, a, MEMTXATTRS_UNSPECIFIED, pk, len);
                    {   /* first packet of each opcode: full hex dump (<= 0x200 B) */
                        static GHashTable* seen;
                        uint16_t op = lduw_le_p(pk + 4);
                        if (!seen) {
                            seen = g_hash_table_new(g_direct_hash, g_direct_equal);
                        }
                        if (!g_hash_table_contains(seen, GUINT_TO_POINTER((guint)op + 1)) || op == 0x0117 ||
                            op == 0x0b01 || op == 0x0b09 || op == 0x0b07 || op == 0x0115) {
                            uint32_t n, m = len < 0x200 ? len : 0x200;
                            GString* gs = g_string_new(NULL);
                            g_hash_table_add(seen, GUINT_TO_POINTER((guint)op + 1));
                            for (n = 0; n < m; n++) {
                                g_string_append_printf(gs, "%02x", pk[n]);
                            }
                            fprintf(stderr, "[ivm-isp] fw: dump op=0x%04x len=0x%x %s\n", op, len, gs->str);
                            g_string_free(gs, TRUE);
                        }
                    }
                    if (ivm_isp_cmd_respond(pk, len, lduw_le_p(pk + 4))) {
                        address_space_write(&ivm_isp_dma_as, a, MEMTXATTRS_UNSPECIFIED, pk, len);
                    }
                    switch (lduw_le_p(pk + 4)) {
                    case 0x0b01: /* primary scaler output config */
                        ivm_isp_out_config(0, pk, len);
                        break;
                    case 0x0b09: /* secondary scaler output config */
                        ivm_isp_out_config(1, pk, len);
                        break;
                    case 0x0100: /* CH_START */
                        ivm_isp_stream(true);
                        break;
                    case 0x0101: /* CH_STOP */
                    case 0x0001: /* STOP */
                    case 0x0021: /* SUSPEND */
                        if (ivm_isp_streaming) {
                            ivm_isp_stream(false);
                        }
                        memset(ivm_isp_bufn, 0, sizeof(ivm_isp_bufn));
                        memset(ivm_isp_poolid, 0, sizeof(ivm_isp_poolid));
                        break;
                    }
                    g_free(pk);
                }
            }
            w0 |= 1;
            ivm_isp_ring_rw(ring, k, &w0, true);
            done |= 1u << ivm_isp_chans[i].src;
        }
    }
    if (done && GPOINTER_TO_UINT(g_hash_table_lookup(ivm_isp_regs, GUINT_TO_POINTER(IVM_ISP_GPIO(0)))) == 0xf7fbdff9u) {
        /* ISP_Suspend: GPIO0 = 0xf7fbdff9 + suspend command -> fw parks and answers 0x8042006 */
        ivm_isp_set(IVM_ISP_GPIO(0), 0x8042006);
        fprintf(stderr, "[ivm-isp] fw: suspend -> parked\n");
    }
    if (done) {
        ivm_isp_pend |= done;
        ivm_isp_set(gb - 0x4000u, ivm_isp_pend);
        if (ivm_isp_irq) {
            qemu_irq_raise(ivm_isp_irq);
        }
    }
}

static void ivm_isp_fw_write(hwaddr off, uint64_t val)
{
    uint32_t i, j, gb;
    if (!ivm_isp_fw_phys) {
        return;
    }
    for (j = 0; j < 2; j++) {
    gb = ivm_isp_gbase[j];
    if (off == IVM_ISP_CPU_RUN && (val & 0x10)) {
        uint8_t tbl[0x100];
        for (i = 0; i < ARRAY_SIZE(ivm_isp_chans); i++) {
            memset(tbl, 0, sizeof(tbl));
            memcpy(tbl, ivm_isp_chans[i].name, strlen(ivm_isp_chans[i].name));
            stl_le_p(tbl + 0x40, ivm_isp_chans[i].type);
            stl_le_p(tbl + 0x44, ivm_isp_chans[i].src);
            stl_le_p(tbl + 0x48, ivm_isp_chans[i].num);
            stl_le_p(tbl + 0x4c, IVM_ISP_RING0 + i * IVM_ISP_RING_STRIDE);
            address_space_write(&address_space_memory, ivm_isp_fw_phys + IVM_ISP_TABLE + i * 0x100,
                                MEMTXATTRS_UNSPECIFIED, tbl, sizeof(tbl));
        }
        if (j == 0) {
            uint32_t k, one = 1;
            for (i = 0; i < ARRAY_SIZE(ivm_isp_chans); i++) {
                for (k = 0; ivm_isp_chans[i].type != 0 && k < ivm_isp_chans[i].num; k++) {
                    ivm_isp_ring_rw(IVM_ISP_RING0 + i * IVM_ISP_RING_STRIDE, k, &one, true);
                }
            }
            ivm_isp_pend = 0;
            fprintf(stderr, "[ivm-isp] fw: CPU released -> wake (%u channels)\n", (unsigned)ARRAY_SIZE(ivm_isp_chans));
        }
        ivm_isp_set(IVM_ISP_GPIO(0), ARRAY_SIZE(ivm_isp_chans));
        ivm_isp_set(IVM_ISP_GPIO(1), 0xfff);
        ivm_isp_set(IVM_ISP_GPIO(3), 0);
        ivm_isp_set(IVM_ISP_GPIO(4), 0);
        ivm_isp_set(IVM_ISP_GPIO(7), 0x8042006);
    } else if (off == IVM_ISP_GPIO(7) && (uint32_t)val == 0xf7fbdff9u) {
        gpointer v = g_hash_table_lookup(ivm_isp_regs, GUINT_TO_POINTER(IVM_ISP_GPIO(0)));
        fprintf(stderr, "[ivm-isp] fw: boot args at 0x%x -> channel table at 0x%x\n", GPOINTER_TO_UINT(v), IVM_ISP_TABLE);
        ivm_isp_set(IVM_ISP_GPIO(0), IVM_ISP_TABLE);
        ivm_isp_set(IVM_ISP_GPIO(1), 0);
        ivm_isp_set(IVM_ISP_GPIO(7), 0x8042006);
    } else if (off == gb + 0x900u) {
        ivm_isp_doorbell(gb, (uint32_t)val);
    } else if (off == gb + 0x90cu) {
        ivm_isp_pend &= ~(uint32_t)val;
        ivm_isp_set(gb - 0x4000u, ivm_isp_pend);
        if (!ivm_isp_pend && ivm_isp_irq) {
            qemu_irq_lower(ivm_isp_irq);
        }
    } else if (off == IVM_ISP_GPIO(3) && (uint32_t)val == 0x8042006u) {
        ivm_isp_set(IVM_ISP_GPIO(3), 0);
        fprintf(stderr, "[ivm-isp] fw: channels armed -> firmware running\n");
    }
    }
}

